### ISSUE TITLE
Name is undefined.

### ISSUE THREAD

**Issue by MatejMecka** [MatejMecka/HacktoberfestStats#14]
When both testing and running the npm module myself MainStat returns name as undefined. Everything else is returned except for the Name which is undefined. 

Your goal is to fix it :D And by fixing it you score a PR. Also i get to test if I have set up CircleCi properly.

Happy Hunting

**Comment by jeromechrist** [comment]
Hello, willing to work on this !

**Comment by kristinn93** [comment]
ah sorry @jeromechrist, forgot to comment when I started working on this. @MatejMecka You can accept his PR,I don't need more Hacktoberfest PRs 😄

**Comment by MatejMecka** [comment]
Thanks @kristinn93 also sorry @jeromechrist :(

**Comment by jeromechrist** [comment]
@MatejMecka @kristinn93 ha, np ! you may want to grab the call to mocha https://github.com/jeromechrist/HacktoberfestStats/blob/db0b9db57fa7afc47ee01d3b3ee48dfaa6d26127/package.json#L7 

npm test was failing for me with the previous call to ./node_modules/mocha/bin/mocha

peace !

**Comment by kristinn93** [comment]
@jeromechrist just out of curiosity what os are you running ?

**Comment by jeromechrist** [comment]
@kristinn93 Windows 10

**Comment by kristinn93** [comment]
@jeromechrist ah could explain why it works fine on mac
