### ISSUE TITLE
Setup prettier to keep code in consistent style

### ISSUE THREAD

**Issue by kristinn93** [MatejMecka/HacktoberfestStats#16]
* Setup [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli) (prettier -> eslint fix)
* Create a .prettierrc file with rules.
* Create a npm script that runs prettier from the command line e.g. `npm run formate`

**Comment by MatejMecka** [comment]
I think I set up eslintr with Circle Ci.
Also, i am running it from the npm test. So should I switch to prettier?

**Comment by kristinn93** [comment]
No `Eslint` tells you if you'r code matches a pattern that is "bad" or some syntax error defined by a ruleset.
`Prettier` is a opinionated formatter, but sometimes there are rules defined by eslint that are not comparable with `prettier` formatting hence `prettier-eslint-cli`, it runs `prettier` on your code and then `eslint --fix`

I'll submit a PR 😄

**Comment by kristinn93** [comment]
Feel free to close this issue if you are happy with this @MatejMecka
