### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by MatejMecka** [MatejMecka/HacktoberfestStats#31]

**Comment by pecfw** [comment]
Happy to update this, if I can have access

**Comment by MatejMecka** [comment]
Sure! Send a pull request and I'll merge it :)

**Comment by pecfw** [comment]
https://github.com/MatejMecka/HacktoberfestStats/pull/32

**Comment by MatejMecka** [comment]
Thanks for the PR. Now it's merged in master!
