### ISSUE TITLE
Issues Scraping Hacktoberfest's site

### ISSUE THREAD

**Issue by MatejMecka** [MatejMecka/HacktoberfestStats#9]
Due to the website being dynamic we are having trouble scraping the website. Your task is to find a way to scrape the site. 

I've thought about rewritting it using PhantomJS but I'm open to ideas :)

Good luck and Have a fun Hacktoberfest!

**Comment by ghost** [comment]
@MatejMecka I would like to propose another approach instead of evaluating JS and scrape the web page: I'll try to call directly the same APIs used by the official webpage.

What do you think about this?

**Comment by MatejMecka** [comment]
Sure that's another great idea too
